# Project-wide Gradle settings
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle for more details.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See https://gradle.org/docs/current/userguide/gradle_daemon.html
# default: -Xmx1024m -XX:MaxPermSize=256m
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. See https://gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and sees the resource IDs within all dependent
# libraries as non-final. If false, all downstream tests use flatPackageNames false and
# the scope of each library's R class includes the resources declared in the library as well as
# the resources declared in all of its dependencies.
android.nonTransitiveRClass=true

# Gradle Daemon
org.gradle.daemon=true

# Build Cache
org.gradle.build.cache=true

# Enable new dependency resolution engine
android.useNewApkCreator=true

# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin settings
kotlin.code.style=official
